import Head from "next/head";
import Layout from "../components/UI/Layout";

export default function Home() {
  return (
      <Layout>
        <div>
          <Head>
            <title>Food</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/Logo.png" />
          </Head>
          {/* body */}
          <main>
            <h1></h1>        
          </main>
        </div>
      </Layout>
  );
}

